### ISSUE TITLE
Could not resolve host: dev.azure.com

### ISSUE THREAD

**Issue by jluqueba** [microsoft/azure-pipelines-ephemeral-agents#2]
A few months ago i was able to complete the sample pipeline and it runs with no problems, but a few days ago when i try to run it, get the error:

Could not resolve host: dev.azure.com

The error appears just after "1. Determining matching Azure Pipelines agent...", in the curl command

**Comment by jluqueba** [comment]
<img width="1659" alt="Untitled" src="https://user-images.githubusercontent.com/10743149/72351678-18cf4600-36e1-11ea-9b03-cee7470e8947.png">

**Comment by tspascoal** [comment]
That is odd to say the least.

Can you login into ACR to try to run this command?

It seems at the container is using a DNS that cannot access public DNS servers. 

Not exactly sure how that could happen, is there any global policy in place to disable public DNS or use private DNS  ?

**Comment by jluqueba** [comment]
It is very very weird.

I try another approach and hardcode de AGENT_PAKAGE_URL and...for a couple of times it works, but then, suddenly came into another error: Could not resolve host vstsagentpackage.azureedge.net.

Don't know if error is in Docker image, in Container or in Virtual Network.

I´m trying to connect to ACI, but at least from Azure Console is impossible (Connection Close in each attempt).

Any idea?

**Comment by tspascoal** [comment]
Connecting to a container its only possible while it's running, i mean if the init script fails and it just stops it an error there is no more container to log into. You will have to change the script to keep running so you can log in and debug.

It definitely seems a DNS issue. Is it always the same VNET? perhaps that particular VNET is not using 
_Default (Azure-provided)_ config for DNS but using custom with a DNS that doesn't solve public DNS?

**Comment by p2bauer** [comment]
I'm also running into exactly this problem - and I've reproduced it was a net-new VNet with no customizations at all other than a new subnet for the container (including default azure dns).  @jluqueba  @tspascoal  did you happen to resolve this issue?  Any suggestions or things I could try?

Here is the yaml I'm using in case it helps:
```
- task: AzureContainerAgentCreate@0
  name: Create_Container_For_Eph_Agent
  displayName: 'Create Az Container for Next Agent Job (in Vnet)'
  continueOnError: false
  inputs:
    azureSubscription: '$(azureSubscription)'
    resourceGroupName: '$(resourceGroup)'
    location: '$(location)'
    azureDevOpsToken: '<token>'
    containerRegistry: '$(containerRegistry)'
    imageName: '<registry_name>.azurecr.io/azurepipelinesbasicdeployagent/linux:<tag_name>'
    agentPool: 'Ephemeral Agents'
    agentPrefix: 'eph-'
    vnetResourceGroupName: '$(resourceGroup)'
    vnetName: '$(vnetName)'
    subnetName: 'ephemeralagents'
    timeoutAgentOnline: '240'
    osType: 'Linux'
    skipContainerDeletionOnError: true
```

![image](https://user-images.githubusercontent.com/6989445/77286941-84a8dd00-6d28-11ea-8f99-5b8e0b16c354.png)
